-- =====================================================
-- TABLE: study_plans
-- Description: Stores AI-generated study plans for subjects
-- =====================================================

create table public.study_plans (
  id uuid not null default gen_random_uuid (),
  user_id uuid not null,
  subject_id uuid not null,
  title text not null,
  description text null,
  generated_date timestamp with time zone not null default now(),
  start_date date not null,
  end_date date not null,
  total_hours integer not null,
  status text not null default 'active'::text,
  projected_pass_chance integer null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  
  constraint study_plans_pkey primary key (id),
  constraint study_plans_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint study_plans_subject_id_fkey foreign key (subject_id) references subjects (id) on delete cascade,
  
  -- Check constraints
  constraint study_plans_title_check check (
    (char_length(title) >= 1)
    and (char_length(title) <= 200)
  ),
  constraint study_plans_description_check check (
    (description is null)
    or (char_length(description) <= 1000)
  ),
  constraint study_plans_status_check check (
    status = any (array['active'::text, 'completed'::text, 'archived'::text])
  ),
  constraint study_plans_total_hours_check check (total_hours > 0),
  constraint study_plans_date_range_check check (end_date >= start_date),
  constraint study_plans_projected_pass_chance_check check (
    (projected_pass_chance is null)
    or (
      (projected_pass_chance >= 0)
      and (projected_pass_chance <= 100)
    )
  )
) tablespace pg_default;

-- =====================================================
-- INDEXES
-- =====================================================

create index if not exists idx_study_plans_user_id 
  on public.study_plans using btree (user_id) tablespace pg_default;

create index if not exists idx_study_plans_subject_id 
  on public.study_plans using btree (subject_id) tablespace pg_default;

create index if not exists idx_study_plans_status 
  on public.study_plans using btree (status) tablespace pg_default;

create index if not exists idx_study_plans_created_at 
  on public.study_plans using btree (created_at desc) tablespace pg_default;

create index if not exists idx_study_plans_user_subject 
  on public.study_plans using btree (user_id, subject_id) tablespace pg_default;

create index if not exists idx_study_plans_end_date 
  on public.study_plans using btree (end_date) tablespace pg_default
  where (status = 'active'::text);

-- =====================================================
-- TRIGGERS
-- =====================================================

create trigger trigger_update_study_plans_updated_at 
  before update on study_plans 
  for each row
  execute function update_updated_at ();

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

alter table public.study_plans enable row level security;

-- Policy: Users can view their own study plans
create policy "Users can view their own study plans"
  on public.study_plans
  for select
  using (auth.uid() = user_id);

-- Policy: Users can create their own study plans
create policy "Users can create their own study plans"
  on public.study_plans
  for insert
  with check (auth.uid() = user_id);

-- Policy: Users can update their own study plans
create policy "Users can update their own study plans"
  on public.study_plans
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Users can delete their own study plans
create policy "Users can delete their own study plans"
  on public.study_plans
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- COMMENTS
-- =====================================================

comment on table public.study_plans is 'Stores AI-generated study plans for subjects with projected outcomes';
comment on column public.study_plans.title is 'The name/title of the study plan';
comment on column public.study_plans.description is 'Optional description or notes about the plan';
comment on column public.study_plans.generated_date is 'When the plan was generated by AI';
comment on column public.study_plans.start_date is 'When the student should start following this plan';
comment on column public.study_plans.end_date is 'Target completion date for the plan (usually before exam)';
comment on column public.study_plans.total_hours is 'Total estimated study hours for completing the plan';
comment on column public.study_plans.status is 'Current status: active, completed, or archived';
comment on column public.study_plans.projected_pass_chance is 'Predicted pass probability if plan is completed (0-100)';
